sudo: false
language: php
services:
- mysql
php:
- '7.2'
- '7.1'
- '7.0'
- '5.6'
env:
- DB=mysql
before_install:
- mkdir -p build/log
- mysql -e 'CREATE DATABASE weathermaptest; GRANT ALL ON weathermaptest.* TO weathermaptest@localhost
  identified by "weathermaptest"; FLUSH PRIVILEGES;'
- cp ./dev/ci/travis-composer.json ./composer.json
install:
- sudo ./dev/ci/travis-dependencies.sh
- composer install
addons:
  code_climate:
    repo_token: 858ba1f597a441ed0b8abfefb2db2ecc09309285da99bd165ebcf1b580ced776
  artifacts:
    debug: true
    target_paths:
    - /${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}
    paths:
    - ./travis-test-results-${TRAVIS_JOB_NUMBER}.zip
    s3_region: eu-west-1
  apt:
    packages:
    - imagemagick
    - rrdtool
    - xsltproc
    - fping
    - zip
before_script:
- mysql weathermaptest < test-suite/data/weathermap-empty.sql
- mysql < lib/Weathermap/Tests/weathermap-seed.sql
- phpenv config-add dev/ci/travis.ini
after_script:
- vendor/bin/test-reporter
- php test-suite/make-failing-summary.php > test-suite/summary-failing.html
- zip -r travis-test-results-${TRAVIS_JOB_NUMBER}.zip test-suite
script:
- vendor/bin/parallel-lint --exclude app --exclude vendor .
- vendor/bin/phpunit --configuration build/phpunit.xml
